---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(maps)
county <- map_data("county")
county_measles <- read.xlsx("county_level_measles.xlsx")
colnames(county_measles)[colnames(county_measles)=="state"] <- "region"
colnames(county_measles)[colnames(county_measles)=="county"] <- "subregion"

map.df <- merge(county,county_measles, by=c("region", "subregion"), all.x=T)

map.df <- map.df[order(map.df$order),]

map.df$my_text=paste("Number of measles cases: " , map.df$cases, sep="")

map.df
plot1 <- ggplot(map.df, aes(x=long,y=lat,group=group, text = my_text))+
  geom_polygon(aes(fill = cases))+
  geom_path()+ 
  scale_fill_gradientn(colours=rev(heat.colors(10)),na.value="grey90")+
  coord_map()


# Make the plot
my_graph=plot_ly(data, x=x , y=y , mode="markers"   , text=my_text , hoverinfo="text+x+y" , marker=list(color="green" , size=20 , opacity=0.4))
my_graph


plot1 <- ggplotly(plot1)


htmlwidgets::saveWidget(plot1, "test.html")



```

